In [2]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [4]:
def mae(y_true,y_predicted):
    total_error = 0
    for yt, yp in zip(y_true,y_predicted):
        total_error += abs(yt - yp)
    print("Total error", total_error)
    
    mae = total_error /len(y_true)
    print("MAE", mae)
    return mae

In [5]:
mae(y_true,y_predicted)

Total error 2.5
MAE 0.5


0.5

In [6]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [7]:
np.sum(np.abs(y_predicted-y_true))

2.5

In [23]:
def mae(y_true,y_predicted):
    total_error = 0
    for yt, yp in zip(y_true,y_predicted):
        total_error += abs(yt - yp)**2
    print("Total error", total_error)
    
    mae = total_error /len(y_true)
    print("MAE", mae)
    return mae

In [24]:
mae(y_true,y_predicted)

Total error 1.83
MAE 0.366


0.366

In [25]:
np.mean(np.square(y_predicted-y_true))

0.366

In [8]:
# mean square error
np.mean(np.abs(y_predicted-y_true)**2)


0.366

In [10]:
#log 0is undefined
np.log([0])

/tmp/ipykernel_11238/2338540976.py:2: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [11]:
epsilon = 1e-15

In [12]:
y_predicted

array([1, 1, 0, 0, 1])

In [14]:
# having 1 replace with value close to 1 but not 1
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [15]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [16]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [17]:
np.log(y_predicted)

/tmp/ipykernel_11238/815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [19]:
# log loss
-np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [21]:
def log_loss(y_true,y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new))

In [22]:
log_loss(y_true,y_predicted)

17.2696280766844