In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
profit = revenue - expenses

In [9]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [5]:
#Broadcasting in numpy ---> demension not same it behaves as illustrated below
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [7]:
price_per_unit = np.array([[1000,400,1200],[1000,400,1200],[1000,400,1200]])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [8]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [10]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [12]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

In [13]:
revenues_usd = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revenues_inr = 75*revenues_usd
revenues_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])