In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
one_hot("amazing restaurant",30)

[10, 12]

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[10, 3], [10, 12], [4, 14], [8, 13, 16], [17, 19, 6], [21, 3], [25, 19, 28], [8, 24], [8, 15], [16, 19]]


In [4]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[10  3  0  0]
 [10 12  0  0]
 [ 4 14  0  0]
 [ 8 13 16  0]
 [17 19  6  0]
 [21  3  0  0]
 [25 19 28  0]
 [ 8 24  0  0]
 [ 8 15  0  0]
 [16 19  0  0]]


In [5]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

2022-01-21 12:04:52.848524: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-01-21 12:04:52.848627: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (tabinda-Inspiron-3542): /proc/driver/nvidia/version does not exist
2022-01-21 12:04:52.850911: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
X = padded_reviews
y = sentiment

In [7]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [8]:
model.fit(X, y, epochs=50, verbose=0)

In [9]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 160ms/step - loss: 0.6301 - accuracy: 1.0000


1.0

In [10]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [11]:
weights[13]

array([-0.05330157, -0.08261453,  0.01854396,  0.01065221, -0.05163369],
      dtype=float32)

In [12]:
weights[4]

array([-0.08302215,  0.03628011,  0.01021617,  0.04891438, -0.08657078],
      dtype=float32)

In [13]:
weights[16]

array([ 0.04345025,  0.05282317, -0.02976217,  0.05391184,  0.09561886],
      dtype=float32)